os: osx
language: generic
osx_image: xcode8.3
before_script:
- pip install six
- brew update
- brew install --HEAD libimobiledevice
- brew install ideviceinstaller
- brew install ios-deploy
- git clone https://github.com/flutter/flutter.git -b alpha --depth 1
script:
- "./flutter/bin/flutter -v build ios --no-codesign"
cache:
  directories:
  - "$HOME/.pub-cache"
deploy:
  provider: releases
  api_key: 39c4bc73647a2f04a8930cf5a1666f378c73ba39
  file: build/ios/iphoneos/app.ipa
  on:
    repo: ghmoha/startupnamer
